# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  test:
    uses: Arlula/python-core-sdk/.github/workflows/python-test.yml@master
    secrets:
      TEST_API_HOST: ${{ secrets.TEST_API_HOST }}
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
      TEST_API_SECRET: ${{ secrets.TEST_API_SECRET }}
      TEST_API_ORDER_KEY: ${{ secrets.TEST_API_ORDER_KEY }}
      TEST_API_ORDER_EULA: ${{ secrets.TEST_API_ORDER_EULA }}
      TEST_API_ORDER_BUNDLE: ${{ secrets.TEST_API_ORDER_BUNDLE }}
      TEST_API_ORDER_ID: ${{ secrets.TEST_API_ORDER_ID }}
      TEST_API_RESOURCE_ID: ${{ secrets.TEST_API_RESOURCE_ID }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
