# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  test:
    uses: Arlula/python-core-sdk/.github/workflows/python-test.yml@master
    env:
      TEST_API_KEY: ${{ secrets.TEST_API_KEY}}
      TEST_API_SECRET: ${{ secrets.TEST_API_SECRET}}
      TEST_API_HOST: ${{ env.TEST_API_HOST}}
      TEST_API_ARCHIVE_ORDERING_ID_1: ${{ env.TEST_API_ARCHIVE_ORDERING_ID_1}}
      TEST_API_ARCHIVE_LICENSE_HREF_1: ${{ env.TEST_API_ARCHIVE_LICENSE_HREF_1}}
      TEST_API_ARCHIVE_BUNDLE_KEY_1: ${{ env.TEST_API_ARCHIVE_BUNDLE_KEY_1}}
      TEST_API_ARCHIVE_ORDERING_ID_2: ${{ env.TEST_API_ARCHIVE_ORDERING_ID_2}}
      TEST_API_ARCHIVE_LICENSE_HREF_2: ${{ env.TEST_API_ARCHIVE_LICENSE_HREF_2}}
      TEST_API_ARCHIVE_BUNDLE_KEY_2: ${{ env.TEST_API_ARCHIVE_BUNDLE_KEY_2}}
      TEST_API_ORDER_ID_CAMPAIGNS: ${{ env.TEST_API_ORDER_ID_CAMPAIGNS}}
      TEST_API_ORDER_ID_DATASETS: ${{ env.TEST_API_ORDER_ID_DATASETS}}
      TEST_API_CAMPAIGN_ID: ${{ env.TEST_API_CAMPAIGN_ID}}
      TEST_API_DATASET_ID: ${{ env.TEST_API_DATASET_ID}}
      TEST_API_RESOURCE_ID: ${{ env.TEST_API_RESOURCE_ID}}
      TEST_API_COLLECTION_ID: ${{ env.TEST_API_COLLECTION_ID}}
      TEST_API_COLLECTION_ITEM_ID: ${{ env.TEST_API_COLLECTION_ITEM_ID}}
      TEST_API_TASKING_ORDERING_ID_1: ${{ env.TEST_API_TASKING_ORDERING_ID_1}}
      TEST_API_TASKING_BUNDLE_KEY_1: ${{ env.TEST_API_TASKING_BUNDLE_KEY_1}}
      TEST_API_TASKING_LICENSE_HREF_1: ${{ env.TEST_API_TASKING_LICENSE_HREF_1}}
      TEST_API_TASKING_PRIORITY_KEY_1: ${{ env.TEST_API_TASKING_PRIORITY_KEY_1}}
      TEST_API_TASKING_CLOUD_1: ${{ env.TEST_API_TASKING_CLOUD_1}}
      TEST_API_TASKING_ORDERING_ID_2: ${{ env.TEST_API_TASKING_ORDERING_ID_2}}
      TEST_API_TASKING_BUNDLE_KEY_2: ${{ env.TEST_API_TASKING_BUNDLE_KEY_2}}
      TEST_API_TASKING_LICENSE_HREF_2: ${{ env.TEST_API_TASKING_LICENSE_HREF_2}}
      TEST_API_TASKING_PRIORITY_KEY_2: ${{ env.TEST_API_TASKING_PRIORITY_KEY_2}}
      TEST_API_TASKING_CLOUD_2: ${{ env.TEST_API_TASKING_CLOUD_2}}
    secrets:
      API_PASS: ${{ secrets.TEST_API_PASS}}
      API_KEY: ${{ secrets.TEST_API_KEY}}
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
